USE [master]
GO

/****** Object:  Database [QuanLyGiaiDauBongDa]    Script Date: 3/25/2022 10:05:31 PM ******/
CREATE DATABASE [QuanLyGiaiDauBongDa]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'QuanLyGiaiDauBongDa', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\QuanLyGiaiDauBongDa.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'QuanLyGiaiDauBongDa_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\QuanLyGiaiDauBongDa_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [QuanLyGiaiDauBongDa].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET ARITHABORT OFF 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET  DISABLE_BROKER 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET RECOVERY FULL 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET  MULTI_USER 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET DB_CHAINING OFF 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET QUERY_STORE = OFF
GO

ALTER DATABASE [QuanLyGiaiDauBongDa] SET  READ_WRITE 
GO


